### ISSUE TITLE
rank deficient when computing covariance of ppp_estimator

### ISSUE THREAD

**Issue by 222233tommy** [chichengcn/gici-open#20]
Hi, Dr. chi, thanks for your amazing work. I try to test the PPP-AR and meet the rank deficient problem of the jacobian matrix. I guess the cause may be related to the constant parameter while the sliding window is not full (jacobian rank = jacobian column -1). It seems that the problem will not occur on GPS-only measurements. Could you please help me with that? Thanks a lot!
![Screenshot from 2023-10-31 11-20-14](https://github.com/chichengcn/gici-open/assets/31362268/d1e88295-94dd-4645-8809-eb1ba15de467)

**Comment by chichengcn** [comment]
We did not extensively test the PPP-AR module. Could you provide the configuration file and the number of datasets?

**Comment by 222233tommy** [comment]
Configuration file:

**Comment by 222233tommy** [comment]
There is another issue when I test the dual-frequency PPP with BDS. IFB for code 27 for system C has not been initialized!

**Comment by chichengcn** [comment]
Thanks for pointing out. We have fixed this BUG and uploaded the codes. This BUG is caused by improper strategy of adding initial constraints for ambiguity and ionosphere parameters. Please note that phase bias product is demanded for PPP-AR algorithm, but we did not provide this product in our dataset. Forcely applying PPP-AR algorithm without phase bias corrections may cause large errors in solutions.

As for the IFB issue, code 27 (BDS B2bI) is not one of the base frequencies (B1I and B3I), however our dual-frequency PPP algorithm was designed for the base frequencies. So perhaps this BUG is foreseeable. But anyway, you can provide the configuration file and the number of dataset. We will focus on this issue in future development.
